name: Generate Docs
on:
  push:
    branches: 
     - main
    paths:
      - '**.java'
      - '.github/workflows/*'
      
  pull_request:
    branches: 
     - main
    paths:
      - '**.java'
      
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (For PR)
        if: ${{ github.event_name == 'pull_request'}}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Checkout (For Push)
        if: ${{ github.event_name != 'pull_request'}}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Generate Elevator Javadocs
        run: javadoc -d docs/javadoc/elevator -notimestamp -sourcepath code/elevator/src/ -subpackages elevator
      - name: Commit Docs
        uses: EndBug/add-and-commit@v8
        with:
          add: 'docs/javadoc'
          author_name: 'Doc Bot'
          committer_name: 'Doc Bot'
          default_author: github_actions
          message: 'Update Docs'




        
